### PR TITLE
Upgrade phpunit to 9 and fix tests. Improve php 8 support 

### PR DESCRIPTION
**Pull request by zorn-v**
As bonus, fixed `Wingu\OctopusCore\Reflection\ReflectionFile::reflect` - `each` function was deprecated in php 7.2 and removed in 8.0 
https://www.php.net/each
And some types was added for "php tokens" in 8.0

One test (`Wingu\OctopusCore\Reflection\Tests\Unit\ReflectionClassUseTest::testGetConflictResolutions`) I mark as skipped, as do not know how to resolve it.

### CODE REVIEW

**Comment by zorn-v** [comment]
Fixed that test.
Actually add support for php 8 to `Wingu\OctopusCore\Reflection\ReflectionClassUse::extractConflictsFromUseStatement`. 
In php 8 added two type constants - T_NAME_QUALIFIED and T_NAME_FULLY_QUALIFIED

**Comment by dragosprotung** [comment]
Thank you @zorn-v. I will have a look in 1-2 days

**Comment by dragosprotung** [comment]
@zorn-v could you please rebase ?

**Comment by zorn-v** [comment]
Done

**Comment by dragosprotung** [comment]
Do you think you could switch to https://github.com/symfony/phpunit-bridge ? This way older PHP versions can be checked.
It's ostly for the feature, as old PHP versions should be dropped

**Comment by zorn-v** [comment]
For php 7.1 I do not know what coverage driver it wants.

There is also deprecations remains - `Method ReflectionParameter::getClass() is deprecated` (https://www.php.net/manual/ru/reflectionparameter.getclass.php), but suggested method `ReflectionParameter::getType` was added only in php 7

**Comment by zorn-v** [comment]
Fixed coverage for php7.1

**Comment by dragosprotung** [comment]
Amazing work @zorn-v, thank you

**Pull request merged**
